module.exports = {
  "printWidth": 100,
  "tabWidth": 2,
  "useTabs": false,
  "semi": true,
  "singleQuote": false,
  "jsxSingleQuote": false,
  "quoteProps": "as-needed",
  "bracketSpacing": true,
  "trailingComma": "none",
  "arrowParens": "always",
  "insertPragma": false,
  "requirePragma": false,
  "proseWrap": "never",
  "htmlWhitespaceSensitivity": "strict",
  "bracketSameLine": true,
  "singleAttributePerLine": true,
  "vueIndentScriptAndStyle": true,
  "endOfLine": "lf"
}
