#!/usr/bin/env bash

HAS_PNPM=true

# 调试等待
function _wait() {
    echo -e "\033[1;32m按任意键继续~\033[0m"
    read -r -n 1
}

function execute() {
    local callback=$1
    if ! command pnpm -v pnpm &>/dev/null; then
        HAS_PNPM=false
        echo -e '\033[1;31m警告Warn：请使用pnpm作为包管理工具，具体版本详情请查阅package.json文件下packageManager字段，已降级使用NPM！\033[0m'
    fi

    # 检查回调函数参数是否存在
    if [ -n "$callback" ] && [ "$(type -t "$callback")" = function ]; then
        $callback "$2"
    fi
    # DEBUG on-off👇
    # _wait
}
